server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native,default,dev  # native file repository
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/workspace.edu/egovframe-msa-edu/config # Windows
#           search-locations: file://${user.home}/workspace.edu/egovframe-msa-edu/config # MacOS
  rabbitmq:
    host: ${rabbitmq.hostname:localhost}
    port: 5672
    username: guest
    password: guest

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh
